apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: karate-debug
  namespace: default
  description: Plugin to aid with creating, managing and debugging karate tests
  title: karate-debug
  tags: []
  links:
    - url: https://github.com/j8d/karate-debug
      title: Repository URL
  annotations:
    backstage.io/techdocs-ref: "dir:."
    sonarqube.org/project-key: "j8d_karate-debug"
    github.com/project-slug: "j8d/karate-debug"

spec:
  type: "module"
  lifecycle: experimental
  owner: patient-core
  dependsOn: []
  providesApis: []
  consumesApis: []
