name: Generate SBOM for GitHub Release

on:
  release:
    types: [ published ]
    
jobs:
  generate-sbom:
    uses: resmed/devx-shared-workflows/.github/workflows/sbom-file-generate.yml@main
    secrets: inherit
