name: PR linters
on: [pull_request]
jobs:
  tag-workflow:
    uses: resmed/devx-shared-workflows/.github/workflows/tag-workflow-for-datadog-ci.yml@main
    secrets: inherit

  lint-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Linting Pull Request
        uses: resmed/devx-action-prcop@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          config-file: ".github/config/prcop-config.json"
        continue-on-error: true
      - name: Label PR Size
        uses: resmed/devx-action-pr-size-labeler@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'Teeny'
          xs_max_size: '10'
          s_label: 'Small'
          s_max_size: '100'
          m_label: 'Medium'
          m_max_size: '500'
          l_label: 'Large'
          l_max_size: '2000'
          xl_label: 'OH LAWD HE COMIN'
          fail_if_xl: 'false'
          message_if_xl: >
            This PR exceeds the recommended size of 2000 lines.
            Please make sure you are NOT addressing multiple issues with one PR.
            Note this PR might be rejected due to its size.

      - name: Lint against JIRA
        uses: resmed/devx-action-jira-lint@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-token: ${{ secrets.DEVX_JIRA_TOKEN }}
          jira-base-url: https://resmedglobal.atlassian.net
        continue-on-error: true
