# See https://docs.devx.resmed.com/learn/build/vending/sync-repo-to-template/
name: Sync repo with DevX template

on:
  schedule:
    - cron: '0 19 10 * *'
  workflow_dispatch:

jobs:
  get-devx-updates:
    uses: resmed/devx-shared-workflows/.github/workflows/sync-template.yml@main
    with:
      template-repo: devx-template-basic
    secrets: inherit